### PR TITLE
Fix `plot.image` input shape

### PR DESCRIPTION
**Pull request by zuoxingdong**

### CODE REVIEW

**Comment by lvdmaaten** [comment]
I think the correct size is `CxHxW`?

**Comment by zuoxingdong** [comment]
@lvdmaaten In the [example](https://github.com/facebookresearch/visdom/blob/master/example/demo.py) it has

```
viz.image(
    np.random.rand(512, 256, 3),
    opts=dict(title='Random!', caption='How random.'),
)
``` 

which I guess it should be `HxWxC`.

**Comment by lvdmaaten** [comment]
Hmmm so then the input format may not be consistent between the Python and the Lua wrapper (as far as I can tell, Lua uses `CxHxW`).

**Comment by ajabri** [comment]
I just committed a pull request to change the python API to use CxHxW as well.

**Pull request closed without merging**
