### PR TITLE
Add Python type stub.

### PR DESCRIPTION
**Pull request by malmaud**
First pass at adding type annotations.

Closes https://github.com/facebookresearch/visdom/issues/388.

### CODE REVIEW

**Comment by JackUrb** [comment]
Seems solid to me - did you get a chance to test with `pyre`?

**Comment by malmaud** [comment]
Not yet, I'll give that a shot.

**Comment by malmaud** [comment]
It does work with pyre in my testing, with the caveat that pyre needs to be explicitly told the directory where the stub lives with the `search_path` option. That won't be necessary once https://github.com/facebook/pyre-check/issues/70 is resolved.

**Comment by malmaud** [comment]
I rebased. I don't think any other changes are needed since #392 didn't change the type information of any `Visdom` arguments, as far as users are concerned.

**Comment by JackUrb** [comment]
Ah fair enough - I recall a time where some of this overlapped with #392 but I suppose that went away with the separate stub file. Thanks!

**Pull request closed without merging**
