### PR TITLE
Edit images to support PNG

### PR DESCRIPTION
**Pull request by gheaeckkseqrz**
##  Description
Edit the images method to support 4 channels image.

## Motivation and Context
Allow to display a batch of pngs.

## How Has This Been Tested?
Used it to display a batch of png, and a batch of regular RGB (to make sure it didn't break)

## Screenshots (if appropriate):
Looks just like before.
The transparent areas are white by defaults when displaying pngs.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] For JavaScript changes, I have re-generated the minified JavaScript code.

### CODE REVIEW

**Comment by Lisicong9203** [comment]
Has this feature been added to the official version? Can it be used in that version?

**Comment by JackUrb** [comment]
It is not yet on pypi, no. There haven't been significant enough changes for a new release

**Comment by Lisicong9203** [comment]
I want to show a png image with four channels[320.320.4] (The fourth channel represents transparency). Is there any good way?

**Comment by Lisicong9203** [comment]
Can png be supported with only one line of code? What i saw here at [https://github.com/fossasia/visdom/commit/341360cfa1327be48db6a7d2995ff953c0d07b68](341360c)

**Comment by JackUrb** [comment]
I'm not sure I understand your question. From the description here, the PR owner tested with PNG and image types without transparency, and found it worked. Based on my understanding of the codebase, indeed a 1 line change was the big issue that prevented PNG (and other 4 channel image types) from working before.

**Pull request closed without merging**
