### PR TITLE
Replace slashes in an environment name to underscores

### LINKED ISSUE #32: Cannot save the environment if it contains slashes
Hi, thank you for the great software first!

I am really enjoying using the software, however I found some trivial bugs that occur in corner cases.
When I try to save an environment which contains slashes, for example "model_1/dim100", it cannot save the environment and makes some unhappy side effects.
If I save it programmatically, for example `vis.save([env_name])`, the server makes error logs of `FileNotFoundError`, since the directory `$HOME/.visdom/model_1` does not exist.
And if I try to save it on the webpage, the webpage goes offline and I have to click the "offline" button or refresh the page to revive functionalities.

I think two solutions are possible:
1) making the directory (using something like `mkdir -p` or `os.makedirs`) before making the JSON file of an environment, or
2) replacing slash characters with other safe characters, like `_`.

### PR DESCRIPTION
**Pull request by jihunchoi**
It fixes #32.

### CODE REVIEW

**Comment by lvdmaaten** [comment]
Can you please make the same change in the Lua wrapper to keep the two in sync?

Character replacement in Lua can be done via `eid = eid:gsub('/', '_')`.

**Comment by ajabri** [comment]
This is fine since it's server-side. Thanks @jihunchoi !

**Comment by ajabri** [comment]
Looks good, could you please rebase your commit on master?

**Comment by jihunchoi** [comment]
Could you explain what I should do more in detail please? There is no conflict with master.

**Pull request closed without merging**
