### PR TITLE
Pull in changes from master into the tsne branch

### PR DESCRIPTION
**Pull request by pringshia**
This is a temp branch to show the results of rebasing the tsne branch onto master as of 6/13/19

### CODE REVIEW

**Comment by JackUrb** [comment]
Something seems to potentially be up with gitignore considering the existence of `__pycache__` files.

**Comment by pringshia** [comment]
> Something seems to potentially be up with gitignore considering the existence of `__pycache__` files.

Also think we need to add `py/visdom/static/js/layout-bin-packer.js` to the gitignore

**Comment by pringshia** [comment]
@JackUrb Fixed. If this looks good to you, I can merge the changes into the `tsne` branch.

**Comment by pringshia** [comment]
Pushed a squashed merge commit to the `tsne` branch: https://github.com/facebookresearch/visdom/pull/611/commits/4bf81c53bc53d5d7903d8ca52b8617349b8503f2

Closing this temp branch.

**Pull request closed without merging**
