### PR TITLE
Deprecating Python 2 support in visdom

### PR DESCRIPTION
**Pull request by JackUrb**
## Description
As a first step towards modernizing the visdom codebase, I'm freeing us from the shackles of python 2 compatibility. Version `v0.1.8.9` was tagged as the last version with python support, and will be left for any users that want to use python 2 with visdom. Future enhancements will be python 3 only.

## Motivation and Context
Python 2 support has become something of a burden (from testing to maintenance to merging new code - #647 and #595 have been blocked by internal python3 issues for a while now). Now 

## How Has This Been Tested?
Run `demo.py` on python3, everything works well! Run `demo.py` on python2, get a notice to downgrade.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] For JavaScript changes, I have re-generated the minified JavaScript code.

### CODE REVIEW

**Comment by pringshia** [comment]
Thanks for pushing this through! I'd suggest we `git tag` the commit before this merge commit so we can easily reference the last time the code was Python 2 compatible (just in case).

**Comment by pringshia** [comment]
Just saw the branch name..... nice 👏

**Comment by JackUrb** [comment]
[Already tagged](https://github.com/facebookresearch/visdom/releases/tag/v0.1.8.9) 👍

**Comment by pringshia** [comment]
Nice! Great minds think alike 😉

**Pull request closed without merging**
