### PR TITLE
Remove cd ns

### PR DESCRIPTION
**Pull request by SelvamArul**
This PR removes the CDN links by downloading the external files as part of post-installation hooks in setup.py. This avoids #133

### CODE REVIEW

**Comment by lvdmaaten** [comment]
Thanks, this is a great start!

I think there are still dependencies on the MathJax CDN left. In particular, [this Javascript](https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_SVG) is pulling in some other JavaScripts. This is going to be a problem as it prints the following warning in the console: `WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.`

Also, the MathJax appears to be expecting some fonts in `static/fonts/`?

**Comment by lvdmaaten** [comment]
@ajabri just pointed out another potential issue: `setup.py` is not run with `pip install` if the package is distributed as a wheel. Which means we probably have to run it at server launch time (which, admittedly, is not a very nice solution).

**Comment by SelvamArul** [comment]
@lvdmaaten I moved the downloading of scripts to server.py and executed before launching the server. This means we don't have access rights to copy the files to visdom installation directory. So I am using `FLAGS.env_path` defined in `server.py` as the download target. To enabling the web server to serve files in this new directory I created a new `StaticFileHandler`. I am not sure this is the best way of doing it.

Now, I have issues with `mathjax-MathJax.js` downloading `extensions/MathMenu.js` which intern downloads more files from the CDN. Apparently, we need to download the whole `MathJax` package. So I am thinking of downloading the whole `MathJax` package from `https://github.com/mathjax/MathJax/archive/2.7.1.zip`. Do you have a suggestion regarding this?

**Comment by lvdmaaten** [comment]
@SelvamArul Thanks, this looks great!

I'm going to need some time to test this internally (right now, it will break our internal visdom setup but I know how to fix it). Why is the `StaticFileHandler` needed? Can't you change the path from which static files are served in https://github.com/facebookresearch/visdom/blob/master/py/server.py#L82?

**Comment by lvdmaaten** [comment]
I just committed an adapted version of your PR. It seems to be working correctly for me. Let me know if you have any problems!

**Comment by SelvamArul** [comment]
@lvdmaaten The installation works. Just a small note regarding MathJax.  I still have this error:
`Uncaught SyntaxError: Unexpected number  MathMenu.js:2`
`Uncaught SyntaxError: Unexpected number  MathZoom.js:2` 

`mathjax-MathJax.js` looks for these files (`"[MathJax]/extensions/MathMenu.js"`). Should we download the whole MathJax package?

**Comment by lvdmaaten** [comment]
@SelvamArul I haven't seen that issue myself (yet), so it would be great if you could send a PR adding downloads of the files we're still missing. I'm okay with downloading the full package. It is probably not exceptionally large, and it would only happens once at server launch anyway.

**Pull request closed without merging**
