### PR TITLE
Modified css to be able to zoom in image.

### PR DESCRIPTION
**Pull request by shubhamjain0594**
Solves issue #55 .

Actual Image
screen shot 2017-07-08 at 11 49 24 am

Before this commit

screen shot 2017-07-08 at 11 49 34 am

After this commit

screen shot 2017-07-08 at 11 54 02 am

### CODE REVIEW

**Comment by ajabri** [comment]
Hi @shubhamjain0594 

Thanks for your pull request! I agree that this is an easy solution.

One hesitation I have is that you can imagine that someone might use the same pane to show different images, e.g. variable sized images as training progresses. In that case,  might it be undesirable for the image to fill the pane? It is sometimes helpful to have a sense of the image's true size.

**Comment by shubhamjain0594** [comment]
Hi @ajabri 

In cases when images are of different sizes, when the panes are created on the visdom window, the size of panes will be different at that time, i.e. each pane will be having the actual size of image. Though on changing the pane size the image size will be change and then it is difficult to get original size. 

So what do yo think might be a better solution? 

Few I have in mind
- Maybe buttons for zooming in and zooming out
- Set the min-width/min-height as the original size of the image.

**Comment by mlajtos** [comment]
How about [zooming on hover](https://www.youtube.com/watch?v=TJ06oyFQjuM)?

**Comment by ajabri** [comment]
@mlajtos looks great to me!

**Comment by lvdmaaten** [comment]
We implemented an alternative to this PR that implements wheel / trackpad zooming and resetting to original size via double-click.

**Pull request closed without merging**
