### PR TITLE
Swaps video encoding from OpenCV to PyAV

### PR DESCRIPTION
**Pull request by andyljones**
This PR swaps OpenCV's video encoding out for PyAV's video encoding.

## Description
The `video` method's had its OpenCV calls replaced with PyAV calls. I've also swapped from OGG(Theora) to MP4(h264), as it has [wider browser support](https://en.wikipedia.org/wiki/HTML5_video#Browser_support). 

## Motivation and Context
OpenCV is [a pain to set up with Theora on Linux](https://github.com/facebookresearch/visdom/issues/335) and it's a pretty hefty library too. This PR swaps it out for PyAV, which [has detailed setup instructions](http://docs.mikeboers.com/pyav/develop/index.html) and is focused exclusively on audio/video IO. 

## How Has This Been Tested?
Ran the demo, all still works on OSX and on Linux.

I've tried to preserve the principal use cases of grayscale and BGR tensors, and floating and uint8 datatypes.

The one hiccup so far is that using `conda install av -c conda-forge` clobbered my numpy install with a conda-forge variant. I don't know if that's normal or just because the virtualenv I was working in was so messy. The use-your-own-ffmpeg instructions worked fine though.

## Screenshots (if appropriate):
N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] For JavaScript changes, I have re-generated the minified JavaScript code.

### CODE REVIEW

**Comment by andyljones** [comment]
@JackUrb Do you prefer single-feature PRs? I think I'm likely to do other bits of work on Visdom as I use it, and I can just batch it all up into a single PR when I'm done if it's easier for you.

**Comment by JackUrb** [comment]
@andyljones - thanks for this! Video in visdom has been something of a pain for a while, and this seems like a pretty good overhaul. I just need to do some testing and ensure this still works internally. Will do a closer code review as well this afternoon.

As far as PRs go, we definitely prefer single feature contained PRs to ones that include a slew of changes, with the caveat that if it's a few loosely related minor changes I don't expect those to be separated out. Single feature PRs are a lot easier to review, though I know they can be a little painful to create if you're writing feature changes in tandem with using the software, so I think this is a pretty happy balance. Large premeditated changes can be in their own PRs, while smaller fixes along the way can be bundled anywhere.

**Comment by NcJie** [comment]
Hi @JackUrb may I know what's the status of this PR?

**Comment by JackUrb** [comment]
Thanks again for this improvement @andyljones, sorry for the really long wait. There were a number of hoops to jump through to get PyAV working internally but things were a bit easier after #674. 

@NcJie it's finally in, sorry for the lack of status updates along the way.

**Pull request closed without merging**
