### PR TITLE
Add new feature Double Y Axis Lines

### PR DESCRIPTION
**Pull request by ubaidsworld**
One can apply two different scales of data on the same linear plot.

## Description
This plot will display two lines with different y axis. Hence, it will help in plot two different arrays with different values together on the same plot.

## Motivation and Context

I want to compare my training and testing data. But that was not feasible using the single line plot. Hence, introduced a new feature.
## How Has This Been Tested?

Here is the code, that I have used for testing it:
```
import visdom
import numpy as np
import time
viz = visdom.Visdom()
viz.delete_env("testing")
viz.env = "testing"
opts=dict(
    side='right',
    nameY1='Training',
    nameY2='Testing',
)
while True:
    X=np.arange(20)
    Y1=np.random.randint(0,20,20)
    Y2=np.random.randint(100,200,20)
    viz.double_yaxis_Lines(X,Y1,Y2,win="test",opts=opts)
    time.sleep(2)
```
## Screenshots (if appropriate):
double_y_axis

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] For JavaScript changes, I have re-generated the minified JavaScript code.

### CODE REVIEW

**Comment by JackUrb** [comment]
Hi @ubaidsworld - thanks for the contribution. Before I review, can you please put the commits of #717 and #718 into this PR? They shouldn't be separate

**Comment by ubaidsworld** [comment]
Hello @JackUrb Thank you for your response. I am new to this sort of process, so I did not know how to put the mentioned commit in one. Hence,I created separate  one. Can you please help me, so I can put them together and next time I will keep that in mind.
Also, please review my this suggestion : #715

**Comment by ubaidsworld** [comment]
I see this:
image

I do not know the reason for this.

**Comment by JackUrb** [comment]
You'll need to first merge the other branches into this one, by changing the revision you are trying to merge into. The other PRs should read "wants to merge 1 commit into ubaidsworld:patch-2 from <other_branch>" if you've done this correctly, and then you'll be allowed to merge those commits into this branch.

If you're making these patches locally in a terminal through git, you can rebase the commits on top of each other in one stack and then push the highest part of the stack.

**Comment by ubaidsworld** [comment]
Thank you @JackUrb . I will close these PRs and create new one with all in one PRs.

**Pull request closed without merging**
