### PR TITLE
Fix issue #34

### PR DESCRIPTION
**Pull request by zuoxingdong**

### CODE REVIEW

**Comment by ajabri** [comment]
Thanks @zuoxingdong ! Could you add the same to the Lua API? It is pretty straight forward if you use: https://github.com/torch/image/blob/master/doc/gui.md#res-imagetodisplaytensorinput-

Otherwise, I can add it after your PR...

**Comment by zuoxingdong** [comment]
@ajabri I've tried to make a Lua version. Could you help if it is correct, since I've never used Lua before.

**Comment by zuoxingdong** [comment]
@ajabri Does it pass the test check ?

**Comment by ajabri** [comment]
Hi @zuoxingdong , sorry I've been swamped in the past few days but I will pull this in and test later today! Apologies!

**Pull request closed without merging**
